profile: dev

spring:
  datasource:
    jdbc-url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password:
  redis:
    host: localhost
    password:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

snowFlake:
  workerId: 0
  datacenterId: 0

logging:
  level:
    com.honeysense: trace
    org.hibernate.SQL: WARN

jwtToken:
  secret: "670C69C5-B2DB-4B11-8F9F-70D12A3495C3"
