profile: dev

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/magpie?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B0&allowPublicKeyRetrieval=true
    username: root
    password: root
  redis:
    host: localhost
    password:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false